# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aea8d78ae856d34c2cab69f70a96c9bac47685265e3d11b5d35f6194fcc8189774466fa31aa05480c788cc5c671dfc192ffd02ca96b3dd0d4e9d48b5cb4ab54f

test:
  secret_key_base: fd9ca70dfeb5b061bd34f3c7c40395532ab22ec7809e26eea848a83dffe01db634448deb7d3cf8a24d145b804db922173faff5055edcbc1b58bfcb3260d47cf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
